import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { listSources } from "@/lib/content-sources/service";
import { createSourceAction, deleteSourceAction, updateSourceAction } from "./actions";

const SourceFields = ({ source }: { source?: Awaited<ReturnType<typeof listSources>>[number] }) => <><Input name="title" defaultValue={source?.title ?? ""} placeholder="Source title" required /><Input name="publisher" defaultValue={source?.publisher ?? ""} placeholder="Publisher" /><Input name="author" defaultValue={source?.author ?? ""} placeholder="Author" /><Input name="url" type="url" defaultValue={source?.url ?? ""} placeholder="https://…" /><select name="sourceType" defaultValue={source?.source_type ?? "website"} className="h-8 rounded-lg border border-input bg-background px-2 text-sm"><option value="website">Website</option><option value="book">Book</option><option value="journal">Journal</option><option value="organization">Organization</option><option value="database">Database</option><option value="other">Other</option></select><Input name="publicationDate" type="date" defaultValue={source?.publication_date ?? ""} /><Input name="accessedDate" type="date" defaultValue={source?.accessed_date ?? ""} /><Input name="notes" defaultValue={source?.notes ?? ""} placeholder="Notes" /> </>;

export default async function AdminSourcesPage({ searchParams }: { searchParams: Promise<{ q?: string; saved?: string; error?: string }> }) {
  const notice = await searchParams;
  const sources = await listSources(notice.q);
  return <section><h2 className="text-xl font-semibold">Sources and references</h2><p className="mt-2 text-sm text-muted-foreground">Manage references reusable across Care Guides and Articles.</p>{notice.saved ? <p className="mt-4 border border-green-700/40 bg-green-500/10 p-3 text-sm">{notice.saved}</p> : null}{notice.error ? <p className="mt-4 border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{notice.error}</p> : null}<form action="/admin/sources" className="mt-4 flex gap-2"><Input name="q" defaultValue={notice.q ?? ""} placeholder="Search sources" /><Button type="submit" variant="outline">Search</Button></form><form action={createSourceAction} className="mt-5 grid gap-3 border border-border bg-card p-4 md:grid-cols-2"><SourceFields /><div className="md:col-span-2"><Button type="submit">Create source</Button></div></form><div className="mt-5 space-y-3">{sources.map((source) => <details key={source.id} className="border border-border bg-card p-4"><summary className="cursor-pointer font-medium">{source.title} <span className="text-sm font-normal text-muted-foreground">· {source.publisher ?? source.url ?? source.source_type}</span></summary><form action={updateSourceAction.bind(null, source.id)} className="mt-4 grid gap-3 md:grid-cols-2"><SourceFields source={source} /><div className="flex justify-end gap-2 md:col-span-2"><Button type="submit">Save</Button><Button formAction={deleteSourceAction.bind(null, source.id)} variant="outline">Delete if unused</Button></div></form></details>)}</div></section>;
}
