/* eslint-disable @next/next/no-img-element */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createContentImageSignedUrls, listContentImages } from "@/lib/content-images/service";
import { deleteImageAction, updateImageAction } from "./actions";

export default async function AdminImagesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [images, notice] = await Promise.all([listContentImages(), searchParams]);
  const urls = await createContentImageSignedUrls(images.map((item) => item.storage_path));
  return <section><h2 className="text-xl font-semibold">Content images</h2><p className="mt-2 text-sm text-muted-foreground">Shared Article and Care Guide uploads. Upload new images from the relevant content editor.</p>{notice.saved ? <p className="mt-4 border border-green-700/40 bg-green-500/10 p-3 text-sm">{notice.saved}</p> : null}{notice.error ? <p className="mt-4 border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{notice.error}</p> : null}<p className="mt-4 text-sm text-muted-foreground">{images.length} images</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{images.map((image) => <article key={image.id} className="border border-border bg-card p-4"><img src={urls.get(image.storage_path)} alt={image.alt_text ?? ""} className="h-48 w-full bg-muted object-contain" /><p className="mt-2 break-all text-xs text-muted-foreground">{image.storage_path}</p><details className="mt-3"><summary className="cursor-pointer font-medium">Edit metadata</summary><form action={updateImageAction.bind(null, image.id)} className="mt-3 grid gap-2"><Input name="altText" defaultValue={image.alt_text ?? ""} placeholder="Alt text" /><Input name="caption" defaultValue={image.caption ?? ""} placeholder="Caption" /><Input name="attribution" defaultValue={image.attribution ?? ""} placeholder="Attribution" /><Input name="author" defaultValue={image.author ?? ""} placeholder="Author" /><Input name="sourceUrl" type="url" defaultValue={image.source_url ?? ""} placeholder="Source URL" /><Input name="licenseName" defaultValue={image.license_name ?? ""} placeholder="License" /><Input name="licenseUrl" type="url" defaultValue={image.license_url ?? ""} placeholder="License URL" /><div className="flex gap-2"><Button type="submit" size="sm">Save metadata</Button><Button formAction={deleteImageAction.bind(null, image.id)} size="sm" variant="outline">Delete if unused</Button></div></form></details></article>)}</div></section>;
}
