import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { listArticleCategories } from "@/lib/taxonomy/service";
import { createCategoryAction, deleteCategoryAction, updateCategoryAction } from "./actions";

export default async function AdminCategoriesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [items, notice] = await Promise.all([listArticleCategories(), searchParams]);
  return <section><h2 className="text-xl font-semibold">Article categories</h2><p className="mt-2 text-sm text-muted-foreground">Manage the broad topics assigned to articles.</p>{notice.saved ? <p className="mt-4 border border-green-700/40 bg-green-500/10 p-3 text-sm">{notice.saved}</p> : null}{notice.error ? <p className="mt-4 border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">{notice.error}</p> : null}<form action={createCategoryAction} className="mt-5 grid gap-3 border border-border bg-card p-4 md:grid-cols-[1fr_2fr_auto]"><Input name="name" placeholder="Category name" required /><Input name="description" placeholder="Description" /><Button type="submit">Create category</Button></form><div className="mt-5 space-y-3">{items.map((item) => <details key={item.id} className="border border-border bg-card p-4"><summary className="cursor-pointer font-medium">{item.name} <span className="text-sm font-normal text-muted-foreground">/{item.slug} · {item.is_active ? "Active" : "Inactive"}</span></summary><form action={updateCategoryAction.bind(null, item.id)} className="mt-4 grid gap-3 md:grid-cols-2"><Input name="name" defaultValue={item.name} required /><Input name="slug" defaultValue={item.slug} required /><textarea name="description" defaultValue={item.description ?? ""} rows={3} className="rounded-lg border border-input bg-background p-2.5 text-sm md:col-span-2" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={item.is_active} /> Active</label><div className="flex justify-end gap-2"><Button type="submit">Save</Button><Button formAction={deleteCategoryAction.bind(null, item.id)} variant="outline">Delete</Button></div></form></details>)}</div></section>;
}
