insert into public.products (
  slug,
  category,
  brand,
  model,
  title,
  description,
  short_description,
  image_url,
  recommended_tank_min_gallons,
  recommended_tank_max_gallons,
  freshwater,
  saltwater,
  planted_tank,
  flow_rate_gph,
  heater_watts,
  light_type,
  light_output,
  substrate_type,
  dimensions,
  price_estimate,
  guide_rating,
  difficulty,
  is_active
)
values
  (
    'fluval-aquaclear-70-power-filter',
    'filters',
    'Fluval',
    'AquaClear 70',
    'Fluval AquaClear 70 Power Filter',
    'Large hang-on-back power filter with adjustable flow and a roomy media basket for medium to large freshwater aquariums.',
    '300 GPH HOB filter for 40-70 gallon tanks.',
    null,
    40,
    70,
    true,
    true,
    true,
    300,
    null,
    null,
    null,
    null,
    null,
    75,
    4.5,
    'beginner',
    true
  ),
  (
    'seachem-tidal-75-power-filter',
    'filters',
    'Seachem',
    'Tidal 75',
    'Seachem Tidal 75 Power Filter',
    'High-flow self-priming hang-on-back filter with large media capacity, adjustable intake, and surface skimming for larger aquariums.',
    '350 GPH HOB filter for up to 75 gallons.',
    null,
    40,
    75,
    true,
    true,
    true,
    350,
    null,
    null,
    null,
    null,
    null,
    85,
    4.5,
    'beginner',
    true
  ),
  (
    'marineland-penguin-350-power-filter',
    'filters',
    'Marineland',
    'Penguin 350',
    'Marineland Penguin 350 Power Filter',
    'Dual BIO-Wheel hang-on-back filter sized for larger community aquariums and moderate to heavy freshwater stocking.',
    '350 GPH BIO-Wheel HOB filter.',
    null,
    50,
    75,
    true,
    true,
    true,
    350,
    null,
    null,
    null,
    null,
    null,
    60,
    4.0,
    'beginner',
    true
  ),
  (
    'aqueon-quietflow-50-led-pro-filter',
    'filters',
    'Aqueon',
    'QuietFlow 50 LED PRO',
    'Aqueon QuietFlow 50 LED PRO Power Filter',
    'Multi-stage hang-on-back filter with cartridge media and LED cartridge change indicator for medium freshwater aquariums.',
    '250 GPH HOB filter for up to 50 gallons.',
    null,
    20,
    50,
    true,
    false,
    true,
    250,
    null,
    null,
    null,
    null,
    null,
    45,
    3.9,
    'beginner',
    true
  ),
  (
    'nicrew-classicled-plus-30-36',
    'lighting',
    'NICREW',
    'ClassicLED Plus 30-36',
    'NICREW ClassicLED Plus 30-36 Inch Aquarium Light',
    'Adjustable white and blue LED aquarium light for 30 to 36 inch freshwater tanks with low to moderate plant needs.',
    'Budget LED light for 30-36 inch tanks.',
    null,
    29,
    40,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'White and blue adjustable LEDs',
    null,
    '30-36 in fixture',
    48,
    4.0,
    'beginner',
    true
  ),
  (
    'hygger-957-planted-36-42',
    'lighting',
    'Hygger',
    '957 Planted 24/7 36-42',
    'Hygger 957 Planted 24/7 Aquarium Light 36-42 Inch',
    'Programmable full-spectrum planted aquarium LED with day-night cycle for common 40 breeder and 50 gallon layouts.',
    'Programmable planted LED for 36-42 inch tanks.',
    null,
    40,
    55,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'Full-spectrum with 24/7 cycle',
    null,
    '36-42 in fixture',
    75,
    4.3,
    'beginner',
    true
  ),
  (
    'fluval-plant-3-0-led-36-46',
    'lighting',
    'Fluval',
    'Plant 3.0 36-46',
    'Fluval Plant 3.0 LED 36-46 Inch Aquarium Light',
    'Programmable high-output full-spectrum LED fixture for larger planted freshwater aquariums and high-light aquascapes.',
    'Premium planted LED for 36-46 inch tanks.',
    null,
    40,
    75,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'High-output full-spectrum planted LED',
    null,
    '36-46 in fixture',
    210,
    4.6,
    'intermediate',
    true
  ),
  (
    'aqueon-deluxe-led-full-hood-24',
    'lighting',
    'Aqueon',
    'Deluxe LED Full Hood 24',
    'Aqueon Deluxe LED Full Hood 24 Inch',
    'Basic full hood with integrated LED lighting for standard 20 high, 15 gallon, and similar 24 inch freshwater aquariums.',
    'LED full hood for standard 24 inch tanks.',
    null,
    15,
    20,
    true,
    false,
    false,
    null,
    null,
    'LED hood',
    'Integrated white LED strip',
    null,
    '24 in hood',
    55,
    3.7,
    'beginner',
    true
  )
on conflict (slug) do update
set
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  title = excluded.title,
  description = excluded.description,
  short_description = excluded.short_description,
  image_url = excluded.image_url,
  recommended_tank_min_gallons = excluded.recommended_tank_min_gallons,
  recommended_tank_max_gallons = excluded.recommended_tank_max_gallons,
  freshwater = excluded.freshwater,
  saltwater = excluded.saltwater,
  planted_tank = excluded.planted_tank,
  flow_rate_gph = excluded.flow_rate_gph,
  heater_watts = excluded.heater_watts,
  light_type = excluded.light_type,
  light_output = excluded.light_output,
  substrate_type = excluded.substrate_type,
  dimensions = excluded.dimensions,
  price_estimate = excluded.price_estimate,
  guide_rating = excluded.guide_rating,
  difficulty = excluded.difficulty,
  is_active = excluded.is_active,
  updated_at = now();
