insert into public.products (
  slug,
  category,
  brand,
  model,
  title,
  description,
  short_description,
  image_url,
  recommended_tank_min_gallons,
  recommended_tank_max_gallons,
  freshwater,
  saltwater,
  planted_tank,
  flow_rate_gph,
  heater_watts,
  light_type,
  light_output,
  substrate_type,
  dimensions,
  price_estimate,
  guide_rating,
  difficulty,
  is_active
)
values
  (
    'aqueon-standard-10-gallon-aquarium',
    'tanks',
    'Aqueon',
    'Standard 10 Gallon',
    'Aqueon Standard Glass Aquarium 10 Gallon',
    'Basic glass aquarium footprint for small freshwater builds, quarantine tanks, shrimp tanks, and beginner community setups.',
    'Simple 10 gallon glass tank.',
    null,
    10,
    10,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    '20.25 x 10.5 x 12.6 in',
    25,
    4.2,
    'beginner',
    true
  ),
  (
    'aqueon-standard-20-gallon-high-aquarium',
    'tanks',
    'Aqueon',
    'Standard 20 High',
    'Aqueon Standard Glass Aquarium 20 Gallon High',
    'Tall 20 gallon glass aquarium suited to small community fish, bettas with tankmates, and planted display tanks with modest footprint needs.',
    'Tall 20 gallon glass tank.',
    null,
    20,
    20,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    null,
    '24.25 x 12.5 x 16.75 in',
    55,
    4.1,
    'beginner',
    true
  ),
  (
    'fluval-flex-15-gallon-aquarium-kit',
    'tanks',
    'Fluval',
    'Flex 15',
    'Fluval Flex 15 Gallon Aquarium Kit',
    'Integrated 15 gallon glass aquarium kit with built-in rear filtration and LED lighting for compact freshwater display builds.',
    '15 gallon kit with filter and light.',
    null,
    15,
    15,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    null,
    '16 x 15 x 15 in',
    165,
    4.4,
    'beginner',
    true
  ),
  (
    'marineland-portrait-5-gallon-aquarium-kit',
    'tanks',
    'Marineland',
    'Portrait 5',
    'Marineland Portrait 5 Gallon Aquarium Kit',
    'Small vertical glass aquarium kit with hidden filtration and LED lighting for bettas, shrimp, or nano aquascapes.',
    'Compact 5 gallon portrait kit.',
    null,
    5,
    5,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    null,
    '9.5 x 9.5 x 14 in',
    80,
    4.0,
    'beginner',
    true
  ),
  (
    'api-aquaview-360-3-gallon-aquarium-kit',
    'tanks',
    'API',
    'Aquaview 360 3 Gallon',
    'API Aquaview 360 3 Gallon Aquarium Kit',
    'Small acrylic aquarium kit for a single betta, shrimp, or temporary desktop setup with very light stocking.',
    'Small 3 gallon desktop kit.',
    null,
    3,
    3,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    '10.2 x 10.2 x 14.5 in',
    45,
    3.2,
    'beginner',
    true
  ),
  (
    'aqueon-standard-40-gallon-breeder-aquarium',
    'tanks',
    'Aqueon',
    'Standard 40 Breeder',
    'Aqueon Standard Glass Aquarium 40 Gallon Breeder',
    'Wide footprint glass aquarium with strong surface area for community tanks, planted layouts, cichlid grow-outs, and flexible aquascaping.',
    'Wide 40 gallon breeder tank.',
    null,
    40,
    40,
    true,
    true,
    true,
    null,
    null,
    null,
    null,
    null,
    '36.19 x 18.25 x 16.94 in',
    130,
    4.6,
    'intermediate',
    true
  ),
  (
    'fluval-aquaclear-20-power-filter',
    'filters',
    'Fluval',
    'AquaClear 20',
    'Fluval AquaClear 20 Power Filter',
    'Hang-on-back power filter with customizable media basket for small freshwater and low to moderate bioload aquariums.',
    '100 GPH HOB filter for 5-20 gallon tanks.',
    null,
    5,
    20,
    true,
    true,
    true,
    100,
    null,
    null,
    null,
    null,
    null,
    35,
    4.4,
    'beginner',
    true
  ),
  (
    'fluval-aquaclear-50-power-filter',
    'filters',
    'Fluval',
    'AquaClear 50',
    'Fluval AquaClear 50 Power Filter',
    'Adjustable hang-on-back filter with large media volume for medium freshwater community tanks and planted aquariums.',
    '200 GPH HOB filter for 20-50 gallon tanks.',
    null,
    20,
    50,
    true,
    true,
    true,
    200,
    null,
    null,
    null,
    null,
    null,
    55,
    4.6,
    'beginner',
    true
  ),
  (
    'seachem-tidal-35-power-filter',
    'filters',
    'Seachem',
    'Tidal 35',
    'Seachem Tidal 35 Power Filter',
    'Self-priming hang-on-back filter with adjustable flow and surface skimmer for small to mid-size aquariums.',
    '130 GPH HOB filter for up to 35 gallons.',
    null,
    10,
    35,
    true,
    true,
    true,
    130,
    null,
    null,
    null,
    null,
    null,
    45,
    4.5,
    'beginner',
    true
  ),
  (
    'seachem-tidal-55-power-filter',
    'filters',
    'Seachem',
    'Tidal 55',
    'Seachem Tidal 55 Power Filter',
    'Mid-size adjustable hang-on-back filter with large media basket, surface skimmer, and self-priming pump.',
    '250 GPH HOB filter for up to 55 gallons.',
    null,
    20,
    55,
    true,
    true,
    true,
    250,
    null,
    null,
    null,
    null,
    null,
    70,
    4.5,
    'beginner',
    true
  ),
  (
    'marineland-penguin-200-power-filter',
    'filters',
    'Marineland',
    'Penguin 200',
    'Marineland Penguin 200 Power Filter',
    'BIO-Wheel hang-on-back filter for common 30 to 50 gallon freshwater aquariums and moderate community stocking.',
    '200 GPH BIO-Wheel HOB filter.',
    null,
    30,
    50,
    true,
    true,
    true,
    200,
    null,
    null,
    null,
    null,
    null,
    45,
    4.0,
    'beginner',
    true
  ),
  (
    'eheim-classic-250-canister-filter',
    'filters',
    'Eheim',
    'Classic 250',
    'Eheim Classic 250 Canister Filter',
    'External canister filter with simple media stack and durable pump design for planted or community aquariums.',
    'Canister filter for roughly 40-65 gallon tanks.',
    null,
    40,
    65,
    true,
    true,
    true,
    116,
    null,
    null,
    null,
    null,
    null,
    130,
    4.3,
    'intermediate',
    true
  ),
  (
    'aqueon-pro-50w-heater',
    'heaters',
    'Aqueon',
    'Pro 50W',
    'Aqueon Pro 50W Submersible Aquarium Heater',
    'Adjustable submersible heater for small tropical freshwater aquariums and betta tanks.',
    '50 watt heater for small tanks.',
    null,
    5,
    20,
    true,
    true,
    true,
    null,
    50,
    null,
    null,
    null,
    null,
    35,
    4.1,
    'beginner',
    true
  ),
  (
    'aqueon-pro-100w-heater',
    'heaters',
    'Aqueon',
    'Pro 100W',
    'Aqueon Pro 100W Submersible Aquarium Heater',
    'Adjustable submersible heater sized for common 20 to 40 gallon tropical aquarium builds.',
    '100 watt heater for mid-size tanks.',
    null,
    20,
    40,
    true,
    true,
    true,
    null,
    100,
    null,
    null,
    null,
    null,
    45,
    4.2,
    'beginner',
    true
  ),
  (
    'fluval-m100-submersible-heater',
    'heaters',
    'Fluval',
    'M100',
    'Fluval M100 Submersible Heater',
    'Slim glass submersible heater for common tropical freshwater aquariums around 30 gallons.',
    '100 watt slim heater.',
    null,
    15,
    30,
    true,
    true,
    true,
    null,
    100,
    null,
    null,
    null,
    null,
    40,
    4.0,
    'beginner',
    true
  ),
  (
    'eheim-jager-150w-heater',
    'heaters',
    'Eheim',
    'Jager 150W',
    'Eheim Jager 150W Aquarium Heater',
    'Adjustable glass heater with recalibration ring for medium tropical freshwater and planted tanks.',
    '150 watt heater for 40-79 gallon tanks.',
    null,
    40,
    79,
    true,
    true,
    true,
    null,
    150,
    null,
    null,
    null,
    null,
    35,
    4.4,
    'beginner',
    true
  ),
  (
    'hygger-100w-submersible-aquarium-heater',
    'heaters',
    'Hygger',
    '100W Submersible',
    'Hygger 100W Submersible Aquarium Heater',
    'Compact adjustable heater with external temperature controller for small and mid-size freshwater aquariums.',
    '100 watt heater with controller.',
    null,
    10,
    30,
    true,
    true,
    true,
    null,
    100,
    null,
    null,
    null,
    null,
    28,
    4.0,
    'beginner',
    true
  ),
  (
    'aqueon-preset-50w-heater',
    'heaters',
    'Aqueon',
    'Preset 50W',
    'Aqueon Preset 50W Aquarium Heater',
    'Preset submersible heater for small tropical freshwater tanks where simple setup is more important than fine adjustment.',
    'Preset 50 watt heater.',
    null,
    5,
    20,
    true,
    false,
    true,
    null,
    50,
    null,
    null,
    null,
    null,
    22,
    3.7,
    'beginner',
    true
  ),
  (
    'nicrew-classicled-plus-18-24',
    'lighting',
    'NICREW',
    'ClassicLED Plus 18-24',
    'NICREW ClassicLED Plus 18-24 Inch Aquarium Light',
    'Adjustable white and blue LED aquarium light for low to medium light freshwater plants and general viewing.',
    'Budget LED light for 18-24 inch tanks.',
    null,
    10,
    20,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'White and blue adjustable LEDs',
    null,
    '18-24 in fixture',
    35,
    4.1,
    'beginner',
    true
  ),
  (
    'nicrew-skyled-plus-24-30',
    'lighting',
    'NICREW',
    'SkyLED Plus 24-30',
    'NICREW SkyLED Plus 24-30 Inch Aquarium Light',
    'Slim full-spectrum LED fixture for freshwater viewing and low to moderate planted tank layouts.',
    'Full-spectrum LED for 24-30 inch tanks.',
    null,
    20,
    29,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'Full-spectrum white, red, green, and blue LEDs',
    null,
    '24-30 in fixture',
    45,
    4.0,
    'beginner',
    true
  ),
  (
    'hygger-957-planted-24-7-24-30',
    'lighting',
    'Hygger',
    '957 Planted 24/7 24-30',
    'Hygger 957 Planted 24/7 Aquarium Light 24-30 Inch',
    'Programmable full-spectrum planted aquarium light with day-night cycle for common 20 long and 29 gallon tanks.',
    'Programmable planted LED light.',
    null,
    20,
    29,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'Full-spectrum with 24/7 cycle',
    null,
    '24-30 in fixture',
    55,
    4.3,
    'beginner',
    true
  ),
  (
    'fluval-plant-3-0-led-24-34',
    'lighting',
    'Fluval',
    'Plant 3.0 24-34',
    'Fluval Plant 3.0 LED 24-34 Inch Aquarium Light',
    'Programmable high-output planted aquarium LED for demanding freshwater aquascapes and larger planted builds.',
    'Programmable planted LED fixture.',
    null,
    20,
    55,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'High-output full-spectrum planted LED',
    null,
    '24-34 in fixture',
    150,
    4.6,
    'intermediate',
    true
  ),
  (
    'aqueon-planted-aquarium-clip-on-led',
    'lighting',
    'Aqueon',
    'Planted Clip-On LED',
    'Aqueon Planted Aquarium Clip-On LED Light',
    'Small clip-on LED fixture for nano planted aquariums, shrimp tanks, and betta tanks.',
    'Clip-on LED for nano planted tanks.',
    null,
    2.5,
    10,
    true,
    false,
    true,
    null,
    null,
    'LED',
    'White, blue, and red planted LEDs',
    null,
    'Clip-on nano fixture',
    32,
    3.9,
    'beginner',
    true
  ),
  (
    'seachem-flourite-red',
    'substrate',
    'Seachem',
    'Flourite Red',
    'Seachem Flourite Red Planted Aquarium Substrate',
    'Porous clay gravel substrate for planted freshwater aquariums that can be used alone or mixed with other gravel.',
    'Iron-rich planted clay gravel.',
    null,
    5,
    75,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    'porous clay gravel',
    '15.4 lb bag',
    28,
    4.4,
    'beginner',
    true
  ),
  (
    'seachem-flourite-black',
    'substrate',
    'Seachem',
    'Flourite Black',
    'Seachem Flourite Black Planted Aquarium Substrate',
    'Dark porous clay gravel substrate for planted freshwater aquariums and high-contrast aquascapes.',
    'Black planted clay gravel.',
    null,
    5,
    75,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    'porous clay gravel',
    '15.4 lb bag',
    30,
    4.5,
    'beginner',
    true
  ),
  (
    'fluval-plant-and-shrimp-stratum',
    'substrate',
    'Fluval',
    'Plant and Shrimp Stratum',
    'Fluval Plant and Shrimp Stratum',
    'Mineral-rich volcanic soil substrate for shrimp tanks, planted nano aquariums, and freshwater aquascapes.',
    'Volcanic planted shrimp substrate.',
    null,
    2.5,
    40,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    'volcanic soil',
    '8.8 lb bag',
    32,
    4.3,
    'beginner',
    true
  ),
  (
    'aqueon-plant-and-shrimp-aquarium-substrate',
    'substrate',
    'Aqueon',
    'Plant and Shrimp Substrate',
    'Aqueon Plant and Shrimp Aquarium Substrate',
    'Clay-based rounded substrate designed for planted freshwater aquariums, shrimp tanks, and natural-looking layouts.',
    'Clay planted substrate for shrimp tanks.',
    null,
    5,
    40,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    'clay gravel',
    '5 lb bag',
    18,
    3.9,
    'beginner',
    true
  ),
  (
    'imagitarium-black-aquarium-sand',
    'substrate',
    'Imagitarium',
    'Black Aquarium Sand',
    'Imagitarium Black Aquarium Sand',
    'Fine black inert sand for freshwater aquariums, bottom dwellers, and planted tanks that use root tabs.',
    'Inert black aquarium sand.',
    null,
    5,
    75,
    true,
    true,
    false,
    null,
    null,
    null,
    null,
    'inert sand',
    '20 lb bag',
    25,
    3.8,
    'beginner',
    true
  ),
  (
    'caribsea-eco-complete-planted-black',
    'substrate',
    'CaribSea',
    'Eco-Complete Planted Black',
    'CaribSea Eco-Complete Planted Aquarium Substrate Black',
    'Mineral-rich planted aquarium substrate with dark color and porous grains for freshwater aquascapes.',
    'Black planted aquarium substrate.',
    null,
    10,
    75,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    'mineralized planted gravel',
    '20 lb bag',
    35,
    4.2,
    'beginner',
    true
  ),
  (
    'hygger-small-tree-trunk-aquarium-ornament',
    'decor',
    'Hygger',
    'Small Tree Trunk Ornament',
    'Hygger Small Tree Trunk Aquarium Ornament',
    'Resin cave ornament that provides cover for small fish, shrimp, and bottom-dwelling species.',
    'Small resin cave ornament.',
    null,
    5,
    30,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    'Approx. 5 x 3 x 4 in',
    15,
    3.8,
    'beginner',
    true
  ),
  (
    'fluval-mopani-driftwood-medium',
    'decor',
    'Fluval',
    'Mopani Driftwood Medium',
    'Fluval Mopani Driftwood Medium',
    'Natural two-tone driftwood piece for freshwater aquascapes, pleco grazing surfaces, and planted tank hardscape.',
    'Natural aquarium driftwood.',
    null,
    10,
    75,
    true,
    false,
    true,
    null,
    null,
    null,
    null,
    null,
    'Natural piece; size varies',
    18,
    4.0,
    'beginner',
    true
  ),
  (
    'marineland-bamboo-aquarium-decor',
    'decor',
    'Marineland',
    'Bamboo Decor',
    'Marineland Bamboo Aquarium Decor',
    'Artificial bamboo-style aquarium decoration for low-maintenance cover and background structure.',
    'Artificial bamboo decor.',
    null,
    5,
    40,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    'Approx. 5 x 4 x 9 in',
    12,
    3.5,
    'beginner',
    true
  ),
  (
    'aqueon-betta-castle-kit-ornament',
    'decor',
    'Aqueon',
    'Betta Castle',
    'Aqueon Betta Castle Aquarium Ornament',
    'Small resin ornament with hide spaces for bettas, nano fish, and shrimp in desktop aquariums.',
    'Small betta hide ornament.',
    null,
    2.5,
    10,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    'Small desktop ornament',
    8,
    3.4,
    'beginner',
    true
  ),
  (
    'penn-plax-spongebob-pineapple-house',
    'decor',
    'Penn-Plax',
    'SpongeBob Pineapple House',
    'Penn-Plax SpongeBob Pineapple House Aquarium Ornament',
    'Licensed resin aquarium ornament that functions as playful cover for small freshwater fish.',
    'Novelty resin hide ornament.',
    null,
    5,
    30,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    'Approx. 3 x 3 x 5 in',
    12,
    3.3,
    'beginner',
    true
  ),
  (
    'imagitarium-stacked-stone-hideaway',
    'decor',
    'Imagitarium',
    'Stacked Stone Hideaway',
    'Imagitarium Stacked Stone Hideaway Aquarium Decor',
    'Stone-look resin cave ornament for cichlids, community fish, shrimp, and bottom dwellers.',
    'Stone-look resin cave.',
    null,
    10,
    55,
    true,
    false,
    false,
    null,
    null,
    null,
    null,
    null,
    'Approx. 7 x 4 x 5 in',
    20,
    3.7,
    'beginner',
    true
  )
on conflict (slug) do update
set
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  title = excluded.title,
  description = excluded.description,
  short_description = excluded.short_description,
  image_url = excluded.image_url,
  recommended_tank_min_gallons = excluded.recommended_tank_min_gallons,
  recommended_tank_max_gallons = excluded.recommended_tank_max_gallons,
  freshwater = excluded.freshwater,
  saltwater = excluded.saltwater,
  planted_tank = excluded.planted_tank,
  flow_rate_gph = excluded.flow_rate_gph,
  heater_watts = excluded.heater_watts,
  light_type = excluded.light_type,
  light_output = excluded.light_output,
  substrate_type = excluded.substrate_type,
  dimensions = excluded.dimensions,
  price_estimate = excluded.price_estimate,
  guide_rating = excluded.guide_rating,
  difficulty = excluded.difficulty,
  is_active = excluded.is_active,
  updated_at = now();
